### ISSUE TITLE
Visibility, scrolling and popup

### ISSUE THREAD

**Issue by aholbreich** [orizens/ngx-infinite-scroll#223]
Scroll and popups do not fit together, also visible in the popup example https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview

On opening of popup
- background disapears
- after popup is closes scroll is rewinded to 0

Im not the expert, but if i got it right this module can only work if the container has size bigger than screen. Means also <body> height need to be 100% in all(?) cases

Not sure if this is a bug of this module, maybe it's a general problem. But how to achive more control and separate behavior of popup from background or how to fix two mentioned issues?

**Comment by orizens** [comment]
hi @aholbreich 
height should be set - either 100% or a fixed height.  
scroll is reset because the popup is destroyed.

**Comment by aholbreich** [comment]
I set 100% height. This is exacly the problem the popup has have sceen hight and the list of elements has e.g. 3 screens..
Any idea how to prevent rewinding?

**Comment by orizens** [comment]
@aholbreich that happens because how this plunkr handles the popup and what happens when it shows/hides. 
the scroll is reset in the popup because the data is reset to its initial state and rendered again.
to pass that, you can save the scroll position and when the pop up shows, scroll to that position (search for element.scrollTo js).
