### ISSUE TITLE
problems with scrolling fast 

### ISSUE THREAD

**Issue by djoufouf** [orizens/ngx-infinite-scroll#265]
hello guys,

I need help with my problem, i have exactly the same problem as this post, when i do a quick scroll down it does not execute each time my function, i do not understand why, someone could help me to solve 

this is the post : https://github.com/orizens/ngx-infinite-scroll/issues/128

and this is my code 

template 
` <div class="search-results"
         infinite-scroll
         [infiniteScrollDistance]="2"
         [infiniteScrollThrottle]="10"
         [infiniteScrollContainer]="selector"
         (scrolled)="onScroll()"
         [scrollWindow]="false">`

compenent

onScroll(){
console.log("scrolled')

thanks in advance 
}

my code

**Comment by orizens** [comment]
please follow https://github.com/orizens/ngx-infinite-scroll/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by yzatgit** [comment]
I had the similar issue, my temporary solution was to set [infiniteScrollDistance] to 6 or even larger in order to make the scrolled event fire earlier and allow more time to render the newly loaded stuff, and the scroll can be back to the correct position. I need to dig deeper to figure out why it happened, but please let me know if adjusting the distance works for you as well.

**Comment by wonkaba** [comment]
I am definitely still experiencing this in 10.0.1. Why did it get closed?

**Comment by wonkaba** [comment]
I am definitely still experiencing this in 10.0.1. Why did it get closed?

**Comment by irekBudzowski** [comment]
Moved to https://github.com/orizens/ngx-infinite-scroll/issues/385
