### ISSUE TITLE
scrolledUp

### ISSUE THREAD

**Issue by logicalsisufaj** [orizens/ngx-infinite-scroll#293]
@orizens  please can you see (scrolledUp) in ngx-infinite-scroll@0.8.4 version? scrolledUp don't work don't fire up don't get the data from array

Please help with this

**Comment by orizens** [comment]
duplicate https://github.com/orizens/ngx-infinite-scroll/issues/292

**Comment by orizens** [comment]
please setup an example with stackblitz

**Comment by fredericojesus** [comment]
@orizens Hey man. So the scroll up feature is still very buggy. The calculations are very wrong.
You can test on your own demo, just try for example a big screen (2k resolution), scroll down a little and then try to scroll up, you will notice scroll up event does not fires. It only fires if you scroll a lot down and then up.
This is a bug in the calculations you are making, because for example in my case I don't have any scroll down to make (chat app) and when I scroll up it never fires the event.
Is it possible for you to take a look into this issue please?

**Comment by thebeard** [comment]
Also experiencing buggy behaviour on `scrolledUp` event. I need to set `infiniteScrollUpDistance` to `9.5` for it to fire.

**Comment by kelvinsleonardo** [comment]
Is there any solution to solve this problem?

**Comment by marjan-georgiev** [comment]
Having the same issue. It can be reproduced on the demo stackblitz: https://stackblitz.com/edit/ngx-infinite-scroll?file=src%2Fapp%2Fapp.component.ts

**Comment by thebeard** [comment]
FWIW, I've been able to build my own infinity scroll, with minimal effort, using the new Angular virtual table scroll

**Comment by fredericojesus** [comment]
@thebeard does it support window scroll ?
