### ISSUE TITLE
1millions data object, add on scrollDown and delete on top

### ISSUE THREAD

**Issue by istiti** [orizens/ngx-infinite-scroll#55]
I think the repo-team have to implement an example of millions rows object (virtual scroll) to simlpify us the utilisation because I don't know how implement something like :http://www.ok-soft-gmbh.com/jqGrid/99999VirtualScroll.htm it add data when scroll on bottom and delete on top, it seems it's very very speed, someone have an idea to realize this stuff ? thanks

**Comment by orizens** [comment]
hi @istiti 
perhaps a solution of virtual scroll is suitable to this. 
Currently, it is out of scope. 
I have an intention of implementing such feature according to [this article](https://developers.google.com/web/updates/2016/07/infinite-scroller)

**Comment by istiti** [comment]
This is awesome, when do you think implement this must-have feature?

**Comment by istiti** [comment]
up, no idea?

I juste writed https://github.com/angular/angular/issues/10776#issuecomment-239738103

**Comment by orizens** [comment]
hi @istiti 
this is rather a quite complex implementation to add. 
Currently, I can't estimate when it can happen.

**Comment by orizens** [comment]
hi @spierala 
ngx-infinite-scroll doesn't deal with virtual lists.  
currently, the best strategy i came up with to determine whether to trigger a "scrolled" event is by calculating the height.
if you have any suggestions for a different/better strategy - feel free to share.

**Comment by blakeinate** [comment]
I have modified the method of triggering an event in a virtual list that @spierala presented to get a (somewhat) working solution to the virtual list problem.


```
addOne = false;

scrollDown() {
    const numOfNewItemsToGet = 50;
    const changedNum = this.addOne === true ? numOfNewItemsToGet + 1 : 
    numOfNewItemsToGet - 1;
    this.addOne = !this.addOne;
    if (this.lastIndex + 1 < this.items.length) {
      if (this.lastIndex + changedNum + 1 > this.items.length) {
        this.lastIndex = this.items.length - 1;
        this.firstIndex = this.lastIndex - 200;
      } else {
        this.lastIndex += changedNum;
        this.firstIndex +=  numOfNewItemsToGet;
      }
      this.displayedItems = this.items.slice(this.firstIndex, this.lastIndex + 1);
    }
  }
```
This alternates the virtual list between two lengths on each "scrolled" event, allowing the next event to be triggered.
I am interested if this solution works for anyone else.

**Comment by marie-dk** [comment]
I implementet ngx-infinite-scroll. I was absolutely sure that it would include a slicer to limit the number of items in the scroll area. I was certain that Google, Microsoft, Disney and other big companies, would not use it otherwise. But much to my surprice, it doesn't.

It makes ngx-infinite-scroll useless for datasets if they are indeed infinite. The amount of memory used by the DOM will quickly increase to an unacceptable level

I know it is not easy to implement, especially if the items are different in height. But it is a big showstopper for many. So a warning in the documentation would really save a lot of people time when deciding whether or not to implement ngx-infinite-scroll in their project.
